name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Cambia esto al nombre de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: DataScience
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3 # Cambia esto a tu versión de Python

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Flask application (optional)
        run: |
          cd Api
          python app.py &

      - name: Build and deploy frontend
        run: |
          cd PredictPage
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./PredictPage/dist # Ajusta según la ubicación de tus archivos estáticos
